### ISSUE TITLE
db

### ISSUE THREAD

**Issue by Amirus** [kiasaki/marks#3]

**Comment by kiasaki** [comment]
Thanks for filling this.

You can create the needed database table by running something close to

```
marks -create-db -postgres-url=$DATABASE_URL
```

as stated in the [https://github.com/kiasaki/marks/blob/master/app.json](https://github.com/kiasaki/marks/blob/master/app.json#L9)

The SQL used is in this file https://github.com/kiasaki/marks/blob/master/create_database.go

I'll add details to the README for it :D

**Comment by Amirus** [comment]
Great work.Thank you for the update.
